version: '2'

services:
  api:
    build:
      context: ./docker-builds/reference-api
      dockerfile: Dockerfile
    image: syncforscience/reference-api
    ports:
     - "8080:8080"
    networks:
     - internal
  tasks:
    build:
      context: ./docker-builds/reference-tasks
      dockerfile: Dockerfile
    image: syncforscience/reference-tasks
    networks:
     - internal

networks:
  internal:
    driver: bridge
