version: '2'

services:
  smart:
    volumes:
     - "/config/defaults:/smart-stub/defaults/"
    networks:
     - proxy-tier
    environment:
     - BASE_URL=https://portal.demo.syncfor.science
     - VIRTUAL_HOST=portal.demo.syncfor.science
     - VIRTUAL_NETWORK=nginx-proxy
     - VIRTUAL_PORT=3000
     - LETSENCRYPT_HOST=portal.demo.syncfor.science
     - LETSENCRYPT_EMAIL=letsencrypt@mg.syncfor.science
  app:
    networks:
     - proxy-tier
    environment:
     - BASE_URL=https://app.demo.syncfor.science
     - VIRTUAL_HOST=app.demo.syncfor.science
     - VIRTUAL_NETWORK=nginx-proxy
     - VIRTUAL_PORT=80
     - LETSENCRYPT_HOST=app.demo.syncfor.science
     - LETSENCRYPT_EMAIL=letsencrypt@mg.syncfor.science


networks:
  proxy-tier:
    external:
      name: nginx-proxy
